static const enum doremi_key part[] =
{
DO,DO,DO,FA,FA,SOL,SOL,DO,LA,
FA,FA,LA,FA,RE,LA_MINOR,SOL,MI,
FA,DO,FA,LA,LA,LA,LA_MINOR,LA,
LA,SOL,SOL,LA,LA_MINOR,LA_MINOR,LA_MINOR,DO,
LA_MINOR,LA,DO,DO,DO,LA,FA,DO,
LA,FA,DO,DO,MI,FA,SOL,LA,
SOL,MI,SOL,FA,FA,FA,FA,FA,
FA,MI,FA,SOL,LA,LA_MINOR,LA_MINOR,LA_MINOR,
LA_MINOR,DO,RE,LA,LA,LA_MINOR,LA,SOL,
SOL,SOL,LA_MINOR,LA,SOL,SOL,FA_MINOR,RE,
RE,RE,SI,SOL,LA,RE,RE,RE,
SI,SOL,LA,RE,SOL,LA,SI,DO,
RE,MI,LA,MI,RE,SI,DO,LA,
SOL,
};
