static const enum doremi_key part[] =
{
DO,RE,MI,DO,FA,MI,RE,SILENCE,SILENCE,
DO,SOL,SOL,SOL,SOL,SILENCE,SILENCE,MI,
DO,FA,MI,RE,SILENCE,SILENCE,DO,SOL,
SOL,SOL,SOL,SOL,LA,SOL,DO,RE,
MI,DO,FA,MI,RE,SILENCE,SILENCE,DO,
SOL,SOL,SOL,SOL,SILENCE,SILENCE,MI,DO,
FA,MI,RE,SILENCE,SILENCE,DO,SOL,SOL,
SOL,SOL,SOL,LA,SOL,DO,MI,SILENCE,
SILENCE,RE,FA,SILENCE,SILENCE,MI,FA,MI,
FA,MI,SOL,MI,DO,
};
