static const enum doremi_key part[] =
{
DO,SOL,SILENCE,DO,SILENCE,DO,RE,MI,FA,
SOL,SILENCE,SOL,SOL,SOL_MINOR,LA_MINOR,DO,SILENCE,
DO,DO,LA_MINOR,SOL_MINOR,LA_MINOR,SILENCE,SOL_MINOR,SOL,
SOL,FA,SILENCE,FA,SOL,SOL_MINOR,SILENCE,SOL,
FA,RE_MINOR,SILENCE,RE_MINOR,FA,SOL,SILENCE,FA,
RE_MINOR,RE,SILENCE,RE,RE_MINOR,FA,FA,SOL,
SOL_MINOR,LA_MINOR,SOL,SOL,SOL,SOL,SILENCE,SOL,
SOL,SOL,SILENCE,SOL,SOL,SOL,SOL,DO,
SOL,SILENCE,DO,SILENCE,DO,RE,MI,FA,
SOL,SILENCE,SOL,SOL,SOL_MINOR,LA_MINOR,DO,SILENCE,
RE_MINOR,RE,SI,SOL,SOL_MINOR,SILENCE,DO,SI,
SOL,SOL,SOL_MINOR,SILENCE,DO,SI,SOL,MI,
FA,SILENCE,SOL_MINOR,SOL,RE_MINOR,DO,RE,SILENCE,
FA,SOL,SILENCE,SOL,SOL,SOL,SOL,DO,
};
