static const enum doremi_key part[] =
{
SOL,LA,SI,LA,SI,DO,SI,LA,SOL,
LA,SI,LA,SOL,SI,LA,LA,LA,
LA,LA,LA,RE,DO,SI,LA,SI,
DO,SI,LA,SOL,LA,SI,LA,SOL,
SI,LA,RE,RE,DO,RE,DO,SI,
RE,RE,RE,RE,RE,RE,DO,RE,
DO,SI,RE,RE,RE,RE,RE,SOL,
LA,SI,LA,SI,DO,SI,
};
