static const enum doremi_key part[] =
{
DO,FA,FA,FA,SOL,FA,FA,FA,SOL,
LA,LA,LA,LA_MINOR,LA,LA,SOL,FA,
FA,FA,FA,FA,MI,RE,DO,DO,
DO,DO,FA,FA,FA,FA,MI,FA,
SOL,SOL,DO,FA,FA,FA,SOL,FA,
FA,FA,SOL,LA,LA,LA,LA_MINOR,LA,
LA,SOL,FA,FA,FA,FA,FA,MI,
RE,DO,DO,DO,DO,FA,FA,FA,
FA,SOL,SOL,FA,
};
