static const enum doremi_key part[] =
{
MI,SOL,RE,DO,RE,MI,SOL,RE,SILENCE,
MI,SOL,RE,DO,SOL,FA,MI,RE,
SILENCE,MI,SOL,RE,DO,RE,MI,SOL,
RE,SILENCE,MI,SOL,RE,DO,SOL,SILENCE,
SOL,FA,MI,FA,MI,DO,FA,MI,
RE,MI,RE,LA,SILENCE,SOL,FA,MI,
FA,MI,DO,SOL,RE,
};
