static const enum doremi_key part[] =
{
  MI,MI,MI,MI,MI,MI,MI,SOL,DO,
  RE,MI,MI,FA,FA,FA,FA,FA,
  MI,MI,MI,MI,RE,RE,MI,RE,
  SOL,SOL,MI,MI,MI,MI,MI,MI,
  MI,SOL,DO,RE,MI,MI,FA,FA,
  FA,FA,FA,MI,MI,MI,SOL,SOL,
  FA,RE,DO,DO,SOL,MI,RE,DO,
  SOL,SOL,SOL,MI,RE,DO,LA,LA,
  LA,FA,MI,RE,SOL,SOL,LA,LA,
  SOL,FA,MI,MI,SOL,MI,RE,DO,
  SOL,SOL,SOL,MI,RE,DO,LA,LA,
  LA,FA,MI,RE,SOL,SOL,LA,SOL,
  FA,RE,DO
};
